services:
  api-gateway:
    image: ea4dc2bf8312
    ports:
      - "${API_GATEWAY_PORTS}"
    networks:
      - internal
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - SPRING_REDIS_HOST=redis-stack
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT}

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "${REDIS_PORTS}"
      - "${REDIS_UI_PORTS}"
    networks:
      - internal

  auth-service-db:
    image: postgres:latest
    ports:
      - "${AUTH_SERVICE_DB_PORTS}"
    networks:
      - internal
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${AUTH_SERVICE_VOLUME}:/var/lib/postgresql/data

  auth-service:
    image: dbc939787cfb
    ports:
      - "${AUTH_SERVICE_GRPC_PORTS}"
    networks:
      - internal
    depends_on:
      - auth-service-db
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_URL=${AUTH_SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
    
  patient-service-db:
    image: postgres:latest
    ports:
     - "${PATIENT_SERVICE_DB_PORTS}"
    networks:
      - internal
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${PATIENT_SERVICE_VOLUME}:/var/lib/postgresql/data

  patient-service:
    image: 1efdc4b80c75
    networks:
      - internal
    depends_on:
      - patient-service-db
    environment:
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=${BILLING_SERVICE_GRPC_PORT}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_URL=${PATIENT_SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL=true
      - SPRING_SQL_INIT_MODE=always
  
  staff-service-db:
    image: postgres:latest
    ports:
      - "${STAFF_SERVICE_DB_PORTS}"
    networks:
      - internal
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${STAFF_SERVICE_VOLUME}:/var/lib/postgresql/data

  staff-service:
    image: ab50d3c3ac4d
    networks:
      - internal
    depends_on:
      - staff-service-db
    environment:
      - AUTH_SERVICE_ADDRESS=auth-service
      - AUTH_SERVICE_GRPC_PORT=${AUTH_SERVICE_GRPC_PORT}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_URL=${STAFF_SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always


networks:
  internal:
    driver: bridge

volumes:
  ${AUTH_SERVICE_VOLUME}:
    external: true
  ${PATIENT_SERVICE_VOLUME}:
    external: true
  ${STAFF_SERVICE_VOLUME}:
    external: true
