services:
  api-gateway:
    image: ea4dc2bf8312
    ports:
      - "8079:8079"
    networks:
      - internal
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
      - SPRING_REDIS_HOST=redis-stack
      - SPRING_REDIS_PORT=6379

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - internal

  auth-service-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - internal
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - 42f0d3948df9c53212318d3fcf05216dd7f0da2c0071ba7c4ce895d6d2147f1b:/var/lib/postgresql/data

  auth-service:
    image: dbc939787cfb
    ports:
      - "9083:9083"
    networks:
      - internal
    depends_on:
      - auth-service-db
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
    
  patient-service-db:
    image: postgres:latest
    ports:
     - "5432:5432"
    networks:
      - internal
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - 7dc1434d98cd64a6ca905ad636b18b2624fe849ec317e4c5032121e378fee09a:/var/lib/postgresql/data

  patient-service:
    image: 1efdc4b80c75
    networks:
      - internal
    depends_on:
      - patient-service-db
    environment:
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9082
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db/postgres
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL=true
      - SPRING_SQL_INIT_MODE=always
  
  staff-service-db:
    image: postgres:latest
    ports:
      - "5435:5432"
    networks:
      - internal
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - 9923b7cd06a45c8f77c434a0fad42df11b8b0f88cd95a926671fb92458c5cd97:/var/lib/postgresql/data

  staff-service:
    image: ab50d3c3ac4d
    networks:
      - internal
    depends_on:
      - staff-service-db
    environment:
      - AUTH_SERVICE_ADDRESS=auth-service
      - AUTH_SERVICE_GRPC_PORT=9083
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://staff-service-db/postgres
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always


networks:
  internal:
    driver: bridge

volumes:
  42f0d3948df9c53212318d3fcf05216dd7f0da2c0071ba7c4ce895d6d2147f1b:
    external: true
  7dc1434d98cd64a6ca905ad636b18b2624fe849ec317e4c5032121e378fee09a:
    external: true
  9923b7cd06a45c8f77c434a0fad42df11b8b0f88cd95a926671fb92458c5cd97:
    external: true
