package com.hms.auth_service.enums;

public enum Role {
    ADMIN, DOCTOR, NURSE, RECEPTIONIST, PHARMACIST, RADIOLOGIST, SECURITY, ACCOUNTANT, DIETICIAN, ANESTHESIOLOGIST, CLEANING_STAFF, PHYSIOTHERAPIST, LAB_TECHNICIAN, SURGEON
}
